import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  Bell,
  BookOpen,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronUp,
  CircleHelp,
  CirclePlus,
  Ellipsis,
  Eraser,
  Eye,
  FilePenLine,
  FileText,
  FolderClosed,
  Handshake,
  Heart,
  HelpCircle,
  House,
  Info,
  LifeBuoy,
  Lock,
  LogOut,
  MailWarning,
  MessageCircle,
  MessageSquare,
  Pencil,
  Plane,
  Plus,
  Search,
  Send,
  Share2,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Settings,
  Tag,
  Trash2,
  Truck,
  User,
  X,
  XCircle
} from "lucide-react-native";

export const lucideIcons = {
  heart: Heart,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  ellipsis: Ellipsis,
  eye: Eye,
  "file-text": FileText,
  "folder-closed": FolderClosed,
  info: Info,
  x: X,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  bell: Bell,
  "sliders-horizontal": SlidersHorizontal,
  "arrow-up-down": ArrowUpDown,
  "alert-circle": AlertCircle,
  "trash-2": Trash2,
  plus: Plus,
  search: Search,
  "share-2": Share2,
  smartphone: Smartphone,
  house: House,
  "help-circle": HelpCircle,
  "life-buoy": LifeBuoy,
  lock: Lock,
  "log-out": LogOut,
  "book-open": BookOpen,
  "message-circle": MessageCircle,
  user: User,
  "circle-plus": CirclePlus,
  "message-square": MessageSquare,
  tag: Tag,
  truck: Truck,
  sparkles: Sparkles,
  star: Star,
  settings: Settings,
  "circle-help": CircleHelp,
  eraser: Eraser,
  pencil: Pencil,
  "check-check": CheckCheck,
  "x-circle": XCircle,
  handshake: Handshake,
  "file-pen-line": FilePenLine,
  "plane": Plane,
  "mail-warning": MailWarning,
  "send": Send,
} as const;

export type LucideIconName = keyof typeof lucideIcons;
