import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronUp,
  CirclePlus,
  Ellipsis,
  Eye,
  FileText,
  FolderClosed,
  Info,
  Heart,
  House,
  MessageCircle,
  MessageSquare,
  SlidersHorizontal,
  Plus,
  ArrowUpDown,
  Search,
  Share2,
  Smartphone,
  Tag,
  Trash2,
  Truck,
  User,
  X,
  Sparkles,
  Star,
  CircleHelp,
} from "lucide-react-native";

export const lucideIcons = {
  heart: Heart,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  ellipsis: Ellipsis,
  eye: Eye,
  "file-text": FileText,
  "folder-closed": FolderClosed,
  info: Info,
  x: X,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "sliders-horizontal": SlidersHorizontal,
  "arrow-up-down": ArrowUpDown,
  "trash-2": Trash2,
  plus: Plus,
  search: Search,
  "share-2": Share2,
  smartphone: Smartphone,
  house: House,
  "message-circle": MessageCircle,
  user: User,
  "circle-plus": CirclePlus,
  "message-square": MessageSquare,
  tag: Tag,
  truck: Truck,
  sparkles: Sparkles,
  star: Star,
  "circle-help": CircleHelp,
} as const;

export type LucideIconName = keyof typeof lucideIcons;
