import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  CirclePlus,
  Ellipsis,
  Eye,
  Info,
  Heart,
  House,
  MessageCircle,
  MessageSquare,
  SlidersHorizontal,
  Plus,
  ArrowUpDown,
  Search,
  Smartphone,
  Tag,
  Trash2,
  User,
  X,
} from "lucide-react-native";

export const lucideIcons = {
  heart: Heart,
  check: Check,
  "chevron-down": ChevronDown,
  ellipsis: Ellipsis,
  eye: Eye,
  info: Info,
  x: X,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "sliders-horizontal": SlidersHorizontal,
  "arrow-up-down": ArrowUpDown,
  "trash-2": Trash2,
  plus: Plus,
  search: Search,
  smartphone: Smartphone,
  house: House,
  "message-circle": MessageCircle,
  user: User,
  "circle-plus": CirclePlus,
  "message-square": MessageSquare,
  tag: Tag,
} as const;

export type LucideIconName = keyof typeof lucideIcons;
